services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wiki-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:rw
      - /app/backend/.venv
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wiki-frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: "http://backend:8000"
    volumes:
      - ./frontend:/app/frontend:rw
      - /app/frontend/.venv
    depends_on:
      - backend
    restart: unless-stopped
